services:
  - type: web
    name: healnova-backend
    env: python
    plan: free
    region: singapore
    rootDir: Backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app

    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9